# Generated by Django 4.1.7 on 2023-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('visitorId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('RegisterNumber', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
